# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 228)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_PN = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PN.setObjectName("lineEdit_PN")
        self.gridLayout.addWidget(self.lineEdit_PN, 1, 1, 1, 1)
        self.pushButton_Buscar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Buscar.setObjectName("pushButton_Buscar")
        self.gridLayout.addWidget(self.pushButton_Buscar, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_resultado_padronizado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado_padronizado.setObjectName(
            "label_resultado_padronizado")
        self.gridLayout.addWidget(self.label_resultado_padronizado, 2, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Code Description Manager v0.01"))
        self.label.setText(_translate("MainWindow", "PN:"))
        self.pushButton_Buscar.setText(_translate("MainWindow", "Procurar PN"))
        self.label_2.setText(_translate("MainWindow", "Codigo Padronizado:"))
        self.label_resultado_padronizado.setText(
            _translate("MainWindow", "Codigo padronizado?"))
